### ISSUE TITLE
[BOJ] 최소 비용 구하기

### ISSUE THREAD

**Issue by kimdevspace** [SSAFY12th/ssafyAlgostudy#260]
문제 링크
https://www.acmicpc.net/problem/1916

풀이 사항
풀이 일자: 2024.00.00
풀이 시간: 00분 00초
채점 결과: 오답/시간 초과/런타임 에러/정답
예상 문제 유형: 구현/BFS/DFS/DP/자료구조/문자열 등
시간: 00 ms
메모리: 00 kb

풀이 방법
(풀이 접근 및 방법에 대한 설명 문제를 풀지 못했다면 어느 곳에서 어려움을 느꼈는지 적어주세요!!)

**Comment by kimdevspace** [comment]
### 문제링크
#259 
### 풀이 사항
- 풀이 일자 : 240920
- 풀이 시간 : 20분
- 채점 결과 : 정답
- 예상 문제 유형 : 최단 경로
- 시간 :  476ms
- 메모리 : 50,720kb
### 풀이 방법
- 테케에 있는 비용들이 모두 양수이므로 다익스트라 알고리즘 사용해서 최단 경로 구하기
**다익스트라**
1. 거리 배열 만들어서 스타트노드는 0으로, 나머지는 MaxValue로 초기 
2. 그리디 알고리즘이므로 우선순위 큐에 cost가 작은 순으로 간선들을 담기
3. 탐색 중 연결된 노드들이 이전 노드들간의 거리보다 작은 값일 경우 pq에 넣

**Comment by sangholee235** [comment]
### 문제링크
#263
### 풀이 사항
- 풀이 일자 : 240922
- 풀이 시간 : 40분
- 채점 결과 : 정답
- 예상 문제 유형 : 최단 경로 구하기
- 시간 :  448ms
- 메모리 : 51,088kb
### 풀이 방법
다익스트라로 시작 정점으로 부터 모든 정점으로의 최단 거리를 구한뒤 목적 정점의 거리를 출력함

**Comment by kro46** [comment]
## 문제링크
#266 

## 풀이 사항
풀이 일자 : 240922
풀이 시간 : 2시간
채점 결과 : 정답
예상 문제 유형 : 최단 경로/ 다익스트라
시간 : 360 ms
메모리 : 46,388 kb


## 풀이 방법
다른 친구들의 풀이 방법을 보면 거의 인접 리스트로 풀었더라..
풀이 방법은 비슷하니 넘어가고 인접행렬로 풀었을 때와 인접리스트로 풀었을 때의 차이점을 설명해볼까함
1. 인접리스트는 중복된 간선(이전 정점과 다음 정점이 같은 간선)에 대한 처리가 불필요, Because 같은 간선이더라도 비용이 다르면 다른 원소로 판단하고 다른 위치에 각자 저장, 어차피 간선의 비용을 업데이트하는 과정에서 같은 간선 중 비용이 작은 것을 선택하기 때문에 중복 간선에 대한 처리를 자연스럽게 수행함. 우리가 고민할 필요 X

2. 인접행렬을 사용한 경우 중복된 간선에 대한 처리가 필요함. 왜냐하면 인접행렬은 단 하나의 값을 원소로 선택하기 때문에 입력을 받는 과정에서 중복된 간선의 비용에 따라 더 작은 것을 원소로 선택하는 조건문이 필요함.

**Comment by chanu2** [comment]
## 문제링크
#282 

## 풀이 사항
풀이 일자 : 2024.09.25
풀이 시간 : 1시간
채점 결과 : 정답
예상 문제 유형 :  다익스트라
시간 : 348ms 
메모리 : 44968kb

## 풀이 방법
- 다익스트라 너무 어렵습니다.
- 강의보면서 따라치면서 했습니다. 
- 인접리스트로 그래프 구현
- 다익스트라를 활용하여 최단경로 구하기

**Comment by haesoooo** [comment]
## 문제링크
#272

## 풀이 사항
풀이 일자 : 2024.09.24
풀이 시간 : 50분
채점 결과 : 정답
예상 문제 유형 :  다익스트라
시간 : 471ms 
메모리 : 51,700kb

## 풀이 방법
- 현 정점에서 방문하지 않은 다른 정점까지의 최단 경로를 모두 찾는다.
- 최소 거리에 대한 노드를 방문할 예정으로 방문 처리하고 현 노드를 걔로 바꾼다
- 걔를 방문해서 갈 때 다른 노드를 넘어서 가는 가중치도 계산해서 Dist 테이블 업데이트

DP와 그리디의 짬뽕,,  개념은 이해되지만 직접 눈감고도 구현할 정도로 능숙해지는게 어려운 것 같다
